-- ============================================================================
-- Freshly Grocery E-Commerce — Migration v2: Categories & Supabase Storage
-- ============================================================================

-- 1. CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::TEXT, NOW())
);

-- Enable RLS on categories
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read categories" ON public.categories;
CREATE POLICY "Anyone can read categories" ON public.categories
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins manage categories" ON public.categories;
CREATE POLICY "Admins manage categories" ON public.categories
    FOR ALL USING (public.is_admin());


-- 2. UPDATE PRODUCTS TABLE WITH CATEGORY_ID FOREIGN KEY
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'category_id'
    ) THEN
        ALTER TABLE public.products ADD COLUMN category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL;
    END IF;
END $$;


-- 3. SEED INITIAL CATEGORIES
INSERT INTO public.categories (name, slug) VALUES
('Fresh Produce', 'fresh-produce'),
('Dairy & Eggs', 'dairy-eggs'),
('Bakery', 'bakery'),
('Beverages', 'beverages'),
('Snacks', 'snacks')
ON CONFLICT (name) DO NOTHING;

-- Map existing product rows to categories where possible
UPDATE public.products p
SET category_id = c.id
FROM public.categories c
WHERE p.category_id IS NULL AND (
    LOWER(p.category) = LOWER(c.name) OR
    (p.category = 'Fresh Produce' AND c.name = 'Fresh Produce') OR
    (p.category = 'Dairy & Eggs' AND c.name = 'Dairy & Eggs') OR
    (p.category = 'Bakery' AND c.name = 'Bakery') OR
    (p.category = 'Beverages' AND c.name = 'Beverages') OR
    (p.category = 'Snacks' AND c.name = 'Snacks')
);


-- 4. SUPABASE STORAGE BUCKET & RLS POLICIES SETUP

-- Create Public Storage Bucket 'product-images'
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'product-images',
    'product-images',
    true,
    2097152, -- 2MB Limit
    ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
ON CONFLICT (id) DO UPDATE SET
    public = true,
    file_size_limit = 2097152;

-- STORAGE OBJECTS RLS POLICIES

-- Policy 1: Public Read Access to Product Images
DROP POLICY IF EXISTS "Public Read Product Images" ON storage.objects;
CREATE POLICY "Public Read Product Images" ON storage.objects
    FOR SELECT USING (bucket_id = 'product-images');

-- Policy 2: Admin Insert Product Images
DROP POLICY IF EXISTS "Admin Upload Product Images" ON storage.objects;
CREATE POLICY "Admin Upload Product Images" ON storage.objects
    FOR INSERT WITH CHECK (
        bucket_id = 'product-images' AND public.is_admin()
    );

-- Policy 3: Admin Update Product Images
DROP POLICY IF EXISTS "Admin Update Product Images" ON storage.objects;
CREATE POLICY "Admin Update Product Images" ON storage.objects
    FOR UPDATE USING (
        bucket_id = 'product-images' AND public.is_admin()
    );

-- Policy 4: Admin Delete Product Images
DROP POLICY IF EXISTS "Admin Delete Product Images" ON storage.objects;
CREATE POLICY "Admin Delete Product Images" ON storage.objects
    FOR DELETE USING (
        bucket_id = 'product-images' AND public.is_admin()
    );
