-- ============================================================================
-- Freshly Grocery E-Commerce — Supabase Complete PostgreSQL & Storage Schema (v3)
-- Idempotent setup for PostgreSQL with RLS, Storage, Coupons & Low Stock Control
-- ============================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. TABLES DEFINITIONS

-- PROFILES (Linked to Supabase Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT NOT NULL DEFAULT '',
    default_address TEXT NOT NULL DEFAULT '',
    role TEXT NOT NULL DEFAULT 'customer' CHECK (role IN ('customer', 'admin')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::TEXT, NOW())
);

-- CATEGORIES
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    slug TEXT UNIQUE NOT NULL
);

-- PRODUCTS CATALOG
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    price NUMERIC(10,2) NOT NULL CHECK (price >= 0),
    stock_quantity INTEGER NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
    low_stock_threshold INTEGER DEFAULT 5 CHECK (low_stock_threshold >= 0),
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    image_url TEXT NOT NULL,
    is_available BOOLEAN NOT NULL DEFAULT true
);

-- COUPONS
CREATE TABLE IF NOT EXISTS public.coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    discount_type TEXT NOT NULL CHECK (discount_type IN ('percentage', 'flat')),
    value NUMERIC(10,2) NOT NULL CHECK (value >= 0),
    min_spend NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (min_spend >= 0),
    expiry_date DATE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::TEXT, NOW())
);

-- ORDERS
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    items JSONB NOT NULL,
    total_amount NUMERIC(10,2) NOT NULL CHECK (total_amount >= 0),
    status TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Processing', 'Out for Delivery', 'Delivered', 'Cancelled')),
    delivery_address TEXT NOT NULL,
    delivery_slot TEXT NOT NULL,
    substitution_pref TEXT NOT NULL DEFAULT 'Refund item' CHECK (substitution_pref IN ('Refund item', 'Allow similar brand', 'Contact me')),
    delivery_person TEXT DEFAULT '',
    fulfillment_notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::TEXT, NOW())
);

-- 3. ENABLE ROW LEVEL SECURITY (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- 4. HELPER FUNCTION TO CHECK IF CURRENT USER IS ADMIN
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. RLS POLICIES

-- PROFILES POLICIES
DROP POLICY IF EXISTS "Users view own profile or admin all" ON public.profiles;
CREATE POLICY "Users view own profile or admin all" ON public.profiles
    FOR SELECT USING (auth.uid() = id OR public.is_admin());

DROP POLICY IF EXISTS "Users update own profile or admin all" ON public.profiles;
CREATE POLICY "Users update own profile or admin all" ON public.profiles
    FOR UPDATE USING (auth.uid() = id OR public.is_admin());

DROP POLICY IF EXISTS "System insert profiles" ON public.profiles;
CREATE POLICY "System insert profiles" ON public.profiles
    FOR INSERT WITH CHECK (true);

-- CATEGORIES POLICIES
DROP POLICY IF EXISTS "Public read categories" ON public.categories;
CREATE POLICY "Public read categories" ON public.categories
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin manage categories" ON public.categories;
CREATE POLICY "Admin manage categories" ON public.categories
    FOR ALL USING (public.is_admin());

-- PRODUCTS POLICIES
DROP POLICY IF EXISTS "Public read products" ON public.products;
CREATE POLICY "Public read products" ON public.products
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin manage products" ON public.products;
CREATE POLICY "Admin manage products" ON public.products
    FOR ALL USING (public.is_admin());

-- COUPONS POLICIES
DROP POLICY IF EXISTS "Public read active coupons" ON public.coupons;
CREATE POLICY "Public read active coupons" ON public.coupons
    FOR SELECT USING (is_active = true OR public.is_admin());

DROP POLICY IF EXISTS "Admin manage coupons" ON public.coupons;
CREATE POLICY "Admin manage coupons" ON public.coupons
    FOR ALL USING (public.is_admin());

-- ORDERS POLICIES
DROP POLICY IF EXISTS "Customers view own orders" ON public.orders;
CREATE POLICY "Customers view own orders" ON public.orders
    FOR SELECT USING (auth.uid() = user_id OR public.is_admin());

DROP POLICY IF EXISTS "Customers insert own orders" ON public.orders;
CREATE POLICY "Customers insert own orders" ON public.orders
    FOR INSERT WITH CHECK (auth.uid() = user_id OR public.is_admin());

DROP POLICY IF EXISTS "Customers cancel pending orders" ON public.orders;
CREATE POLICY "Customers cancel pending orders" ON public.orders
    FOR UPDATE USING (
        (auth.uid() = user_id AND status = 'Pending') OR public.is_admin()
    )
    WITH CHECK (
        (auth.uid() = user_id AND status = 'Cancelled') OR public.is_admin()
    );

DROP POLICY IF EXISTS "Admin full control on orders" ON public.orders;
CREATE POLICY "Admin full control on orders" ON public.orders
    FOR ALL USING (public.is_admin());


-- 6. AUTOMATIC PROFILE CREATION TRIGGER ON SIGNUP
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, email, full_name, phone, default_address, role)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'full_name', SPLIT_PART(NEW.email, '@', 1)),
        COALESCE(NEW.raw_user_meta_data->>'phone', ''),
        COALESCE(NEW.raw_user_meta_data->>'default_address', ''),
        CASE 
            WHEN LOWER(NEW.email) = 'admin@fresh.com' THEN 'admin'
            ELSE COALESCE(NEW.raw_user_meta_data->>'role', 'customer')
        END
    )
    ON CONFLICT (id) DO UPDATE SET
        email = EXCLUDED.email,
        full_name = COALESCE(EXCLUDED.full_name, public.profiles.full_name),
        phone = COALESCE(EXCLUDED.phone, public.profiles.phone),
        default_address = COALESCE(EXCLUDED.default_address, public.profiles.default_address),
        role = CASE 
            WHEN LOWER(EXCLUDED.email) = 'admin@fresh.com' THEN 'admin'
            ELSE public.profiles.role
        END;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- 7. SUPABASE REALTIME PUBLICATION SETUP FOR ORDERS
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'orders'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
    END IF;
END $$;


-- 8. STORAGE BUCKET & RLS POLICIES FOR PRODUCT IMAGES
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'product-images',
    'product-images',
    true,
    2097152,
    ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
ON CONFLICT (id) DO UPDATE SET
    public = true,
    file_size_limit = 2097152;

DROP POLICY IF EXISTS "Public Read Product Images" ON storage.objects;
CREATE POLICY "Public Read Product Images" ON storage.objects
    FOR SELECT USING (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Admin Upload Product Images" ON storage.objects;
CREATE POLICY "Admin Upload Product Images" ON storage.objects
    FOR INSERT WITH CHECK (bucket_id = 'product-images' AND public.is_admin());

DROP POLICY IF EXISTS "Admin Update Product Images" ON storage.objects;
CREATE POLICY "Admin Update Product Images" ON storage.objects
    FOR UPDATE USING (bucket_id = 'product-images' AND public.is_admin());

DROP POLICY IF EXISTS "Admin Delete Product Images" ON storage.objects;
CREATE POLICY "Admin Delete Product Images" ON storage.objects
    FOR DELETE USING (bucket_id = 'product-images' AND public.is_admin());


-- 9. SEED DATA
INSERT INTO public.categories (name, slug) VALUES
('Fresh Produce', 'fresh-produce'),
('Dairy & Eggs', 'dairy-eggs'),
('Bakery', 'bakery'),
('Beverages', 'beverages'),
('Snacks', 'snacks')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.products (title, price, stock_quantity, low_stock_threshold, category_id, image_url, is_available) VALUES
('Organic Honeycrisp Apples (1kg)', 4.99, 45, 5, 1, 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=500&auto=format&fit=crop&q=80', true),
('Fresh Hass Avocados (Pack of 3)', 3.49, 4, 5, 1, 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=500&auto=format&fit=crop&q=80', true),
('Whole Milk Organic (1 Gal)', 4.29, 20, 5, 2, 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=500&auto=format&fit=crop&q=80', true),
('Free-Range Large Eggs (12pk)', 3.99, 50, 10, 2, 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=500&auto=format&fit=crop&q=80', true),
('Artisanal Sourdough Bread', 5.49, 2, 5, 3, 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=500&auto=format&fit=crop&q=80', true),
('Cold Pressed Orange Juice (1L)', 4.79, 25, 5, 4, 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=500&auto=format&fit=crop&q=80', true)
ON CONFLICT DO NOTHING;

INSERT INTO public.coupons (code, discount_type, value, min_spend, expiry_date, is_active) VALUES
('FRESH20', 'percentage', 20.00, 35.00, '2026-12-31', true),
('WELCOME10', 'flat', 10.00, 25.00, '2026-12-31', true),
('ORGANIC5', 'flat', 5.00, 15.00, '2026-12-31', true)
ON CONFLICT (code) DO NOTHING;
