-- ============================================================================
-- Freshly Grocery E-Commerce — Migration v3: Admin Portal & Coupons Engine
-- ============================================================================

-- 1. ADD LOW STOCK THRESHOLD TO PRODUCTS TABLE
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'low_stock_threshold'
    ) THEN
        ALTER TABLE public.products ADD COLUMN low_stock_threshold INTEGER DEFAULT 5 CHECK (low_stock_threshold >= 0);
    END IF;
END $$;

-- 2. ADD DRIVER NAME, FULFILLMENT NOTES & COUPON DETAILS TO ORDERS TABLE
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = 'orders' AND column_name = 'fulfillment_notes'
    ) THEN
        ALTER TABLE public.orders ADD COLUMN fulfillment_notes TEXT DEFAULT '';
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = 'orders' AND column_name = 'delivery_person'
    ) THEN
        ALTER TABLE public.orders ADD COLUMN delivery_person TEXT DEFAULT '';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = 'orders' AND column_name = 'coupon_code'
    ) THEN
        ALTER TABLE public.orders ADD COLUMN coupon_code TEXT DEFAULT '';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = 'orders' AND column_name = 'discount_amount'
    ) THEN
        ALTER TABLE public.orders ADD COLUMN discount_amount NUMERIC(10,2) DEFAULT 0;
    END IF;
END $$;

-- 3. CREATE COUPONS TABLE
CREATE TABLE IF NOT EXISTS public.coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    discount_type TEXT NOT NULL CHECK (discount_type IN ('percentage', 'flat')),
    value NUMERIC(10,2) NOT NULL CHECK (value >= 0),
    min_spend NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (min_spend >= 0),
    expiry_date DATE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::TEXT, NOW())
);

-- Enable RLS on coupons
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read active coupons" ON public.coupons;
CREATE POLICY "Public read active coupons" ON public.coupons
    FOR SELECT USING (is_active = true OR public.is_admin());

DROP POLICY IF EXISTS "Admin manage coupons" ON public.coupons;
CREATE POLICY "Admin manage coupons" ON public.coupons
    FOR ALL USING (public.is_admin());

-- 4. SEED SAMPLE PROMOTIONAL COUPONS
INSERT INTO public.coupons (code, discount_type, value, min_spend, expiry_date, is_active) VALUES
('FRESH20', 'percentage', 20.00, 35.00, '2026-12-31', true),
('WELCOME10', 'flat', 10.00, 25.00, '2026-12-31', true),
('ORGANIC5', 'flat', 5.00, 15.00, '2026-12-31', true)
ON CONFLICT (code) DO NOTHING;
